//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Ce code source a été automatiquement généré par Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Agence_de_voyage__Application_.Consultation {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Consultation_HotelSoap", Namespace="http://tempuri.org/")]
    public partial class Consultation_Hotel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VerificationAgencePartenaireOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerificationSaisieUtilisateurOperationCompleted;
        
        private System.Threading.SendOrPostCallback VillesDisponiblesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FourchettePrixOperationCompleted;
        
        private System.Threading.SendOrPostCallback nbHotelSelonCriteresOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHotelsSelonCriteresOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetImageFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Consultation_Hotel() {
            this.Url = global::Agence_de_voyage__Application_.Properties.Settings.Default.Agence_de_voyage__Application__Consultation_Consultation_Hotel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VerificationAgencePartenaireCompletedEventHandler VerificationAgencePartenaireCompleted;
        
        /// <remarks/>
        public event VerificationSaisieUtilisateurCompletedEventHandler VerificationSaisieUtilisateurCompleted;
        
        /// <remarks/>
        public event VillesDisponiblesCompletedEventHandler VillesDisponiblesCompleted;
        
        /// <remarks/>
        public event FourchettePrixCompletedEventHandler FourchettePrixCompleted;
        
        /// <remarks/>
        public event nbHotelSelonCriteresCompletedEventHandler nbHotelSelonCriteresCompleted;
        
        /// <remarks/>
        public event getHotelsSelonCriteresCompletedEventHandler getHotelsSelonCriteresCompleted;
        
        /// <remarks/>
        public event GetImageFileCompletedEventHandler GetImageFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificationAgencePartenaire", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Msg VerificationAgencePartenaire(string idAgence, string password) {
            object[] results = this.Invoke("VerificationAgencePartenaire", new object[] {
                        idAgence,
                        password});
            return ((Msg)(results[0]));
        }
        
        /// <remarks/>
        public void VerificationAgencePartenaireAsync(string idAgence, string password) {
            this.VerificationAgencePartenaireAsync(idAgence, password, null);
        }
        
        /// <remarks/>
        public void VerificationAgencePartenaireAsync(string idAgence, string password, object userState) {
            if ((this.VerificationAgencePartenaireOperationCompleted == null)) {
                this.VerificationAgencePartenaireOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificationAgencePartenaireOperationCompleted);
            }
            this.InvokeAsync("VerificationAgencePartenaire", new object[] {
                        idAgence,
                        password}, this.VerificationAgencePartenaireOperationCompleted, userState);
        }
        
        private void OnVerificationAgencePartenaireOperationCompleted(object arg) {
            if ((this.VerificationAgencePartenaireCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificationAgencePartenaireCompleted(this, new VerificationAgencePartenaireCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerificationSaisieUtilisateur", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Msg VerificationSaisieUtilisateur(int numeroSaisie, string city, string startDate, string endDate, string price, string capacity, string reservation) {
            object[] results = this.Invoke("VerificationSaisieUtilisateur", new object[] {
                        numeroSaisie,
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity,
                        reservation});
            return ((Msg)(results[0]));
        }
        
        /// <remarks/>
        public void VerificationSaisieUtilisateurAsync(int numeroSaisie, string city, string startDate, string endDate, string price, string capacity, string reservation) {
            this.VerificationSaisieUtilisateurAsync(numeroSaisie, city, startDate, endDate, price, capacity, reservation, null);
        }
        
        /// <remarks/>
        public void VerificationSaisieUtilisateurAsync(int numeroSaisie, string city, string startDate, string endDate, string price, string capacity, string reservation, object userState) {
            if ((this.VerificationSaisieUtilisateurOperationCompleted == null)) {
                this.VerificationSaisieUtilisateurOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerificationSaisieUtilisateurOperationCompleted);
            }
            this.InvokeAsync("VerificationSaisieUtilisateur", new object[] {
                        numeroSaisie,
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity,
                        reservation}, this.VerificationSaisieUtilisateurOperationCompleted, userState);
        }
        
        private void OnVerificationSaisieUtilisateurOperationCompleted(object arg) {
            if ((this.VerificationSaisieUtilisateurCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerificationSaisieUtilisateurCompleted(this, new VerificationSaisieUtilisateurCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VillesDisponibles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VillesDisponibles() {
            object[] results = this.Invoke("VillesDisponibles", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VillesDisponiblesAsync() {
            this.VillesDisponiblesAsync(null);
        }
        
        /// <remarks/>
        public void VillesDisponiblesAsync(object userState) {
            if ((this.VillesDisponiblesOperationCompleted == null)) {
                this.VillesDisponiblesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVillesDisponiblesOperationCompleted);
            }
            this.InvokeAsync("VillesDisponibles", new object[0], this.VillesDisponiblesOperationCompleted, userState);
        }
        
        private void OnVillesDisponiblesOperationCompleted(object arg) {
            if ((this.VillesDisponiblesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VillesDisponiblesCompleted(this, new VillesDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FourchettePrix", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FourchettePrix() {
            object[] results = this.Invoke("FourchettePrix", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FourchettePrixAsync() {
            this.FourchettePrixAsync(null);
        }
        
        /// <remarks/>
        public void FourchettePrixAsync(object userState) {
            if ((this.FourchettePrixOperationCompleted == null)) {
                this.FourchettePrixOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFourchettePrixOperationCompleted);
            }
            this.InvokeAsync("FourchettePrix", new object[0], this.FourchettePrixOperationCompleted, userState);
        }
        
        private void OnFourchettePrixOperationCompleted(object arg) {
            if ((this.FourchettePrixCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FourchettePrixCompleted(this, new FourchettePrixCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/nbHotelSelonCriteres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Msg nbHotelSelonCriteres(string city, string startDate, string endDate, string price, string capacity) {
            object[] results = this.Invoke("nbHotelSelonCriteres", new object[] {
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity});
            return ((Msg)(results[0]));
        }
        
        /// <remarks/>
        public void nbHotelSelonCriteresAsync(string city, string startDate, string endDate, string price, string capacity) {
            this.nbHotelSelonCriteresAsync(city, startDate, endDate, price, capacity, null);
        }
        
        /// <remarks/>
        public void nbHotelSelonCriteresAsync(string city, string startDate, string endDate, string price, string capacity, object userState) {
            if ((this.nbHotelSelonCriteresOperationCompleted == null)) {
                this.nbHotelSelonCriteresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnbHotelSelonCriteresOperationCompleted);
            }
            this.InvokeAsync("nbHotelSelonCriteres", new object[] {
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity}, this.nbHotelSelonCriteresOperationCompleted, userState);
        }
        
        private void OnnbHotelSelonCriteresOperationCompleted(object arg) {
            if ((this.nbHotelSelonCriteresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.nbHotelSelonCriteresCompleted(this, new nbHotelSelonCriteresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getHotelsSelonCriteres", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Hotel[] getHotelsSelonCriteres(string city, string startDate, string endDate, string price, string capacity) {
            object[] results = this.Invoke("getHotelsSelonCriteres", new object[] {
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity});
            return ((Hotel[])(results[0]));
        }
        
        /// <remarks/>
        public void getHotelsSelonCriteresAsync(string city, string startDate, string endDate, string price, string capacity) {
            this.getHotelsSelonCriteresAsync(city, startDate, endDate, price, capacity, null);
        }
        
        /// <remarks/>
        public void getHotelsSelonCriteresAsync(string city, string startDate, string endDate, string price, string capacity, object userState) {
            if ((this.getHotelsSelonCriteresOperationCompleted == null)) {
                this.getHotelsSelonCriteresOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHotelsSelonCriteresOperationCompleted);
            }
            this.InvokeAsync("getHotelsSelonCriteres", new object[] {
                        city,
                        startDate,
                        endDate,
                        price,
                        capacity}, this.getHotelsSelonCriteresOperationCompleted, userState);
        }
        
        private void OngetHotelsSelonCriteresOperationCompleted(object arg) {
            if ((this.getHotelsSelonCriteresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHotelsSelonCriteresCompleted(this, new getHotelsSelonCriteresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetImageFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetImageFile(string fileName) {
            object[] results = this.Invoke("GetImageFile", new object[] {
                        fileName});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetImageFileAsync(string fileName) {
            this.GetImageFileAsync(fileName, null);
        }
        
        /// <remarks/>
        public void GetImageFileAsync(string fileName, object userState) {
            if ((this.GetImageFileOperationCompleted == null)) {
                this.GetImageFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImageFileOperationCompleted);
            }
            this.InvokeAsync("GetImageFile", new object[] {
                        fileName}, this.GetImageFileOperationCompleted, userState);
        }
        
        private void OnGetImageFileOperationCompleted(object arg) {
            if ((this.GetImageFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImageFileCompleted(this, new GetImageFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Msg {
        
        private string msgField;
        
        private int codeField;
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ville {
        
        private string nomField;
        
        private string codePostalField;
        
        /// <remarks/>
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public string codePostal {
            get {
                return this.codePostalField;
            }
            set {
                this.codePostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Adresse {
        
        private string numeroField;
        
        private string rueField;
        
        private Ville villeField;
        
        private string positionGPSField;
        
        /// <remarks/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string rue {
            get {
                return this.rueField;
            }
            set {
                this.rueField = value;
            }
        }
        
        /// <remarks/>
        public Ville ville {
            get {
                return this.villeField;
            }
            set {
                this.villeField = value;
            }
        }
        
        /// <remarks/>
        public string positionGPS {
            get {
                return this.positionGPSField;
            }
            set {
                this.positionGPSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Localisation {
        
        private string paysField;
        
        private Adresse adresseField;
        
        /// <remarks/>
        public string pays {
            get {
                return this.paysField;
            }
            set {
                this.paysField = value;
            }
        }
        
        /// <remarks/>
        public Adresse adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Hotel {
        
        private string idField;
        
        private string nomField;
        
        private Localisation localisationField;
        
        private string classementField;
        
        private string capaciteField;
        
        private string prixField;
        
        private string infoHotelField;
        
        private string imgChambreField;
        
        private byte[] fileField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string nom {
            get {
                return this.nomField;
            }
            set {
                this.nomField = value;
            }
        }
        
        /// <remarks/>
        public Localisation localisation {
            get {
                return this.localisationField;
            }
            set {
                this.localisationField = value;
            }
        }
        
        /// <remarks/>
        public string classement {
            get {
                return this.classementField;
            }
            set {
                this.classementField = value;
            }
        }
        
        /// <remarks/>
        public string capacite {
            get {
                return this.capaciteField;
            }
            set {
                this.capaciteField = value;
            }
        }
        
        /// <remarks/>
        public string prix {
            get {
                return this.prixField;
            }
            set {
                this.prixField = value;
            }
        }
        
        /// <remarks/>
        public string infoHotel {
            get {
                return this.infoHotelField;
            }
            set {
                this.infoHotelField = value;
            }
        }
        
        /// <remarks/>
        public string imgChambre {
            get {
                return this.imgChambreField;
            }
            set {
                this.imgChambreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificationAgencePartenaireCompletedEventHandler(object sender, VerificationAgencePartenaireCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificationAgencePartenaireCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificationAgencePartenaireCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Msg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Msg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerificationSaisieUtilisateurCompletedEventHandler(object sender, VerificationSaisieUtilisateurCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerificationSaisieUtilisateurCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerificationSaisieUtilisateurCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Msg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Msg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VillesDisponiblesCompletedEventHandler(object sender, VillesDisponiblesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VillesDisponiblesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VillesDisponiblesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void FourchettePrixCompletedEventHandler(object sender, FourchettePrixCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FourchettePrixCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FourchettePrixCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void nbHotelSelonCriteresCompletedEventHandler(object sender, nbHotelSelonCriteresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class nbHotelSelonCriteresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal nbHotelSelonCriteresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Msg Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Msg)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getHotelsSelonCriteresCompletedEventHandler(object sender, getHotelsSelonCriteresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHotelsSelonCriteresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHotelsSelonCriteresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Hotel[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Hotel[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetImageFileCompletedEventHandler(object sender, GetImageFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImageFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImageFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591